In [1]:
import pandas as pd

In [5]:
info = {
   "name" : ["fatimah","huzi","hamza","amna"],
    "cgpa" :[3.72,3.69,3.99,3.55]
    
}
print(pd.DataFrame(info))

      name  cgpa
0  fatimah  3.72
1     huzi  3.69
2    hamza  3.99
3     amna  3.55

In [6]:
import numpy as np

In [9]:
arr = np.array([[1,2,3],[3,2,1]])
print(pd.DataFrame(arr, columns = ['f','h','v']))

   f  h  v
0  1  2  3
1  3  2  1

In [19]:
df = pd.read_csv("globalAirQuality.csv")
df.head()
df.tail()
df.sample()
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [24]:
#rows
df.loc[0:2]
df.iloc[0:2]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969

In [32]:
# column
df[["city","aqi"]]
#row+column
df.loc[0:2,["city","aqi"]]
df.iloc[0:2,11]

0    108
1     90
Name: aqi, dtype: int64

In [44]:
#FILTERING DATA
df[(df["aqi"]>100)&(df["temperature"]>30)][["city","aqi"]]

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]